export const AUDIT_PLAN_ID = "aiya-system-compatibility-reliability-release-readiness-v1";
export const AUDIT_PLAN_VERSION = "1.0.0";
export const PHASE_4_ID = "phase-4";

export const PHASE_4_STAGES = [
  {
    id: "4.1",
    title: "Worker girisleri, lease, retry ve idempotency sozlesmelerini sabitle",
    prerequisiteStageIds: ["phase-3-closed"],
    requiredOutputFiles: ["worker-contract-matrix.json"],
    objective: "Tum media, audio, AI ve lifecycle worker girislerinin release manifestiyle ve calisma dongusuyle birebir uyumunu kanitlamak.",
    scope: "app/scripts/worker-*.mjs, app/src/lib/*worker*.ts, worker CLI'lari, app/package.json worker scriptleri ve build-release-artifact.mjs worker manifesti.",
    prerequisites: ["Phase 3 state CLOSED", "Phase 3 stage evidence ve output digestleri gecerli", "Repo HEAD okunabilir"],
    affectedComponents: ["worker entry wrappers", "durable queue claim/lease", "retry ve terminal outcome akislari", "worker release manifesti"],
    affectedFiles: ["app/package.json", "app/scripts/worker-*.mjs", "app/scripts/build-release-artifact.mjs", "app/src/lib/phase-85-stage-4b3-*worker*.ts", "app/src/lib/phase-85-stage-4b4-*worker*.ts", "app/src/lib/phase-85-stage-4c-run-service.ts"],
    architectureDecisions: [
      "Uzun calisan worker ile tek batch calistiran --once modu ayni wrapper tarafindan secilir.",
      "Durable processing worker'i claim + lease renewal + terminal completion/failure + retry yolunu gostermeden PASS olamaz.",
      "Lifecycle worker'lari retention/purge ve object operation lease'ini; processing worker'lari queue claim/lease'ini ayri kanitlar.",
      "Worker'lar service-role istemcisini yalnizca server-side CLI sinirinda olusturur; client bundle veya browser yolu audit kapsaminda kabul edilmez.",
    ],
    operations: [
      "Release manifestindeki her worker id, normal command ve --once command'i app/package.json scriptlerine birebir eslestir.",
      "Her worker wrapper'inda --once secenegi, kontrollu interval/forwarding ve child failure durumunda non-zero process exit oldugunu dogrula.",
      "Media, audio transcription/bridge ve AI processing worker'larinda claim, lease token, lease renewal, completion/failure ve retry/terminal outcome marker'larini kaynak dosyadan cikar.",
      "Lifecycle worker'larinda retention/purge/delete ve object operation claim/release yolunu kaynak dosyadan cikar.",
      "Worker CLI'larinda NEXT_PUBLIC_SUPABASE_URL ve SUPABASE_SERVICE_ROLE_KEY zorunlu env kontrolu ile session persistence kapali istemci ayarini dogrula.",
      "Worker girisleri, release manifesti ve source digestlerini secret-free matrix icinde kaydet.",
    ],
    technicalMethods: ["AST yerine kontrollu source-marker scan", "package.json JSON parse", "release manifest command reconciliation", "SHA-256 source digest"],
    dataFlow: "release manifest -> npm worker script -> mjs wrapper -> typed worker CLI -> Supabase service-role client -> claim/lease -> provider/storage -> terminal outcome.",
    dependencies: ["Phase 3 closure evidence", "app/package.json", "app/scripts/build-release-artifact.mjs", "worker source files"],
    errorAndBoundaryCases: ["missing once script", "missing env", "child process non-zero exit", "lease renewal failure", "retry budget exhausted", "lifecycle worker ile processing worker markerlarinin karistirilmasi"],
    tests: ["production-worker-release-contracts.test.ts", "phase-85-stage-4b3-local-worker-runner.test.ts", "phase-85-stage-4b3-media-lifecycle-runner.test.ts", "phase-85-stage-4b3-bundle-worker-outcomes.test.ts", "phase-85-stage-4b4-transcription-worker.test.ts", "phase-85-stage-4b4-durable-transcript-bridge-worker.test.ts", "phase-85-stage-4c-lifecycle.test.ts"],
    verificationCriteria: ["release worker mapping blocker sayisi sifir", "all wrapper checks PASS", "all processing/lifecycle marker checks PASS", "targeted worker suite PASS"],
    completionCriteria: "worker-contract-matrix.json status PASS ve bu stage evidence VERIFIED olmadan 4.2 acilmaz.",
  },
  {
    id: "4.2",
    title: "Mesajlasma, webhook, ledger ve teslimat sozlesmelerini dogrula",
    prerequisiteStageIds: ["4.1"],
    requiredOutputFiles: ["messaging-contract-matrix.json"],
    objective: "WhatsApp/channel ingress, event normalization, idempotent ledger, tenant routing, quarantine ve outbound receipt/retry davranisini tek sozlesmede birlestirmek.",
    scope: "WhatsApp webhook route ve real contract'lari, channel normalizer/ledger/routing, mock adapter, messaging integration/receipt/replay kaynaklari.",
    prerequisites: ["4.1 VERIFIED", "worker matrix digest gecerli"],
    affectedComponents: ["WhatsApp webhook", "channel event ledger", "payload normalizer", "tenant/account routing", "delivery receipt ve retry"],
    affectedFiles: ["app/src/app/api/whatsapp/webhook/route.ts", "app/src/app/api/commercial/webhook/route.ts", "app/src/lib/whatsapp-*", "app/src/lib/phase-85-if-c-channel-event-*", "app/src/lib/phase-85-stage-4b2-*messaging*", "app/src/lib/channel-adapters.ts"],
    architectureDecisions: [
      "Ingress raw payload once normalize edilir; provider event id ledger idempotency anahtaridir.",
      "Signature/canonical gate gecilmeden tenant lookup, AI isleme veya outbound side effect baslamaz.",
      "Unknown/ambiguous identity quarantine edilir; duplicate event ikinci kez gonderim veya AI isleme olusturmaz.",
      "Delivery state geriye donmez; definite temporary failure retry edilir, ambiguous transport unknown olarak kalir.",
      "Real provider egress explicit env gate olmadan acilmaz; mevcut audit kosusu mock/local ile sinirlidir.",
    ],
    operations: [
      "WhatsApp challenge ve HMAC signature kontrollerini raw body seviyesinde dogrula.",
      "WhatsApp/cloud payload normalization ile canonical event schema ve provider account selector eslesmesini dogrula.",
      "Event ledger provider event id/idempotency key, duplicate suppression ve processed/replay kararlarini dogrula.",
      "Tenant/channel identity routing, unknown/ambiguous quarantine ve empty/malformed payload fail-closed davranisini dogrula.",
      "Outbound receipt state monotonicligi, temporary/permanent/ambiguous failure ayrimi ve retry budgetini dogrula.",
      "Mock ve real channel contract gate'lerinin birbirinden ayrildigini, testlerde real egress bulunmadigini kanitla.",
    ],
    technicalMethods: ["HMAC/timing-safe signature contract", "canonical payload normalization", "ledger idempotency scan", "replay corpus test", "receipt transition matrix"],
    dataFlow: "provider webhook -> raw signature/challenge gate -> normalized candidate -> ledger/idempotency -> tenant route/quarantine -> inbound orchestration -> outbound receipt/retry.",
    dependencies: ["worker contract matrix", "channel schema/types", "WhatsApp real contract", "mock replay corpus"],
    errorAndBoundaryCases: ["missing signature", "malformed payload", "duplicate provider id", "unknown or ambiguous account", "empty body", "out-of-order delivery status", "ambiguous network result"],
    tests: ["phase-77ab-whatsapp-cloud-payload-normalization.test.ts", "phase-77ac-whatsapp-mock-webhook.test.ts", "phase-77ad-whatsapp-channel-policy-mock.test.ts", "phase-77ag-channel-replay-rehearsal.test.ts", "phase-77ah-whatsapp-adapter-evidence-closure.test.ts", "phase-85-if-c-channel-event-ledger.test.ts", "phase-85-if-c-channel-event-normalizer.test.ts", "phase-85-if-c-channel-event-routing.test.ts", "phase-85-stage-4b2-messaging-integration.test.ts", "phase-85-stage-4b2-receipt-lifecycle.test.ts", "phase-85-stage-4b2-remediation-r5-evidence.test.ts", "whatsapp-real-contracts.test.ts", "whatsapp-real-migration-contract.test.ts"],
    verificationCriteria: ["all ingress and delivery checks PASS", "real egress is not enabled", "targeted messaging suite PASS", "no duplicate side-effect blocker"],
    completionCriteria: "messaging-contract-matrix.json status PASS ve stage evidence VERIFIED olmadan 4.3 acilmaz.",
  },
  {
    id: "4.3",
    title: "AI provider, prompt context ve run orchestration guvenligini kapat",
    prerequisiteStageIds: ["4.2"],
    requiredOutputFiles: ["ai-contract-matrix.json"],
    objective: "Prompt/context allowlist, klinik risk routing, provider egress gate, timeout/retry, source-backed answer validation ve AI run event lifecycle'ini tek kanitla dogrulamak.",
    scope: "mock/local AI provider, Z.ai/GLM gate, context gateway, AI chat provider/service/store/worker ve run event multiplexer.",
    prerequisites: ["4.2 VERIFIED", "messaging matrix digest gecerli"],
    affectedComponents: ["AI provider boundary", "prompt context gateway", "risk routing", "AI chat durable job", "SSE/realtime event stream"],
    affectedFiles: ["app/src/lib/ai-provider.ts", "app/src/lib/phase-75-zai-provider-gate.ts", "app/src/lib/phase-85-stage-4c-provider.ts", "app/src/lib/phase-85-stage-4c-context-gateway.ts", "app/src/lib/phase-85-stage-4c-run-service.ts", "app/src/lib/phase-85-stage-4c-store.ts", "app/src/lib/phase-85-stage-4c-run-event-multiplexer.ts", "app/src/lib/phase-85-stage-4c-run-worker-cli.ts"],
    architectureDecisions: [
      "Provider'e raw prompt, raw health message ve kontrol disi metadata yerine allowlisted bounded context gonderilir.",
      "Red risk provider'a gitmez; yellow internal draft/handoff ile sinirli; green source-backed ve send guard'li olur.",
      "Provider gercek egress explicit approval/env gate olmadan kapali; audit kosusu deterministic mock/local provider ile yapilir.",
      "AI run claim/lease/event sequence/terminal outcome ayni tenant ve run identity icinde tutulur.",
      "Realtime kanal koparsa bounded catch-up ve exponential poll fallback kullanilir; event sequence geriye gitmez.",
    ],
    operations: [
      "Provider input segment allowlist, segment count/length limitleri ve raw prompt/capsule reddini dogrula.",
      "Red/yellow/green risk kararlarini ve source-backed answerability kosullarini statik ve test kanitiyla dogrula.",
      "Z.ai GLM-5.3-Flash direct paid API gate'ini, real provider flag'ini ve forbidden surface listesini kontrol et.",
      "Provider timeout, retry/error normalization, abort/deadline ve lease heartbeat akislarini dogrula.",
      "Source claim validation, insufficient/conflicting evidence ve medical safety terminal outcome'larini dogrula.",
      "AI job idempotency/lease completion-failure ve run event sequence/realtime catch-up davranisini dogrula.",
    ],
    technicalMethods: ["bounded context marker scan", "risk/provider gate scan", "safe metadata inspection", "durable job lifecycle scan", "event sequence test"],
    dataFlow: "tenant run -> context gateway -> bounded provider request -> provider result -> source/claim validation -> run events -> terminal outcome.",
    dependencies: ["messaging contract matrix", "Phase 75 provider gate", "Phase 76/70 context allowlist", "Stage 4C run store"],
    errorAndBoundaryCases: ["red risk", "unsourced claim", "provider timeout", "provider policy violation", "lease loss", "cancel request", "realtime channel failure", "conflicting evidence"],
    tests: ["ai-provider.test.ts", "phase-75-zai-provider-gate.test.ts", "phase-76i-prompt-context-guard.test.ts", "scope-guard-provider.test.ts", "phase-85-stage-4c-lifecycle.test.ts", "phase-85-stage-4c-remediation-closure.test.ts", "phase-85-stage-4c-run-event-multiplexer.test.ts", "phase-85-stage-4c-service.test.ts", "phase-85-stage-4c-run-service.test.ts", "use-ai-chat.test.ts"],
    verificationCriteria: ["provider boundary blockers sifir", "red risk provider call yok", "raw prompt/completion retention zero contracti mevcut", "targeted AI suite PASS"],
    completionCriteria: "ai-contract-matrix.json status PASS ve stage evidence VERIFIED olmadan 4.4 acilmaz.",
  },
  {
    id: "4.4",
    title: "Media/audio admission, transport, provider ve retention baglantilarini dogrula",
    prerequisiteStageIds: ["4.3"],
    requiredOutputFiles: ["media-contract-matrix.json"],
    objective: "Image/audio admission, hash ve sanitized object key, bounded transport/range, vision/transcription provider gate, quality/review/retry ve retention akisini kanitlamak.",
    scope: "Stage 4B3 visual media ve Stage 4B4 audio/transcription kaynaklari, durable worker'lar, storage/transport, provider/mock ve lifecycle saga'lari.",
    prerequisites: ["4.3 VERIFIED", "AI matrix digest gecerli"],
    affectedComponents: ["media admission", "audio canonicalization", "storage transport", "vision provider", "transcription provider", "quality/review", "object retention"],
    affectedFiles: ["app/src/lib/phase-85-stage-4b3-*.ts", "app/src/lib/phase-85-stage-4b4-*.ts", "app/src/lib/production-ai-media-security-migration-contract.test.ts"],
    architectureDecisions: [
      "Media/audio object provider'a gitmeden MIME, size, hash, canonical/source authority ve sanitized key admission'undan gecmelidir.",
      "Download/range transport bounded olur; content hash ve tenant/object identity ile kayit eslesmesi yapilir.",
      "Vision/transcription real provider egress explicit gate olmadan kapali; mock provider test evidence'i zorunludur.",
      "Provider/storage/observation failure kalite sonucu, retry veya review_required terminal sinifina donusturulur.",
      "Retention/revoke/delete object operation lease ve terminal status ile idempotent calisir.",
    ],
    operations: [
      "Image/audio admission MIME, size, extension/canonical form, content hash ve tenant-bound metadata kontrollerini dogrula.",
      "Sanitized storage object key, content download ve bounded range/stream davranisini dogrula.",
      "Vision/transcription provider gate'lerinin mock-only audit kosusunda ve explicit real-egress kapisi arkasinda oldugunu dogrula.",
      "Durable media/transcription worker claim, lease renewal, provider deadline, retry ve terminal review/failed outcome'larini dogrula.",
      "Observation/transcript validation, source authority, quality gate ve human review etiketlerini dogrula.",
      "Media/audio lifecycle retention, revoke, purge ve object-delete release yolunu idempotent olarak dogrula.",
    ],
    technicalMethods: ["file admission contract scan", "hash/object-key scan", "bounded range test", "mock provider gate scan", "quality/retry lifecycle tests"],
    dataFlow: "channel ingress -> media/audio admission -> sanitized storage -> claimed worker -> bounded provider/mock -> observation/transcript quality gate -> message bundle/review -> retention purge.",
    dependencies: ["AI provider gate", "worker contract matrix", "channel normalized media metadata", "Supabase RPC/storage ports"],
    errorAndBoundaryCases: ["unsupported MIME", "oversized object", "missing hash", "invalid key", "range overflow", "provider disabled", "provider timeout", "observation validation failure", "lease conflict", "delete failure"],
    tests: ["phase-85-stage-4b-integration-verification.test.ts", "all Stage 4B3 media/admission/transport/provider/lifecycle tests", "all Stage 4B4 audio/admission/transport/provider/transcription/lifecycle tests", "production-ai-media-security-migration-contract.test.ts"],
    verificationCriteria: ["media and audio static checks PASS", "real media/AI egress disabled", "all selected Stage 4B3/4B4 tests PASS", "no raw health-media leakage blocker"],
    completionCriteria: "media-contract-matrix.json status PASS ve stage evidence VERIFIED olmadan 4.5 acilmaz.",
  },
  {
    id: "4.5",
    title: "Worker-messaging-AI-media birlesik kapanisini ve Phase 5 kilidini yap",
    prerequisiteStageIds: ["4.1", "4.2", "4.3", "4.4"],
    requiredOutputFiles: ["worker-messaging-ai-media-closure.json"],
    objective: "Onceki dort matrixin digestlerini, final contract suitesini ve Phase 4 mutation boundary'sini tekrar kontrol ederek fazi kapatmak.",
    scope: "Phase 4 output/evidence dosyalari, final targeted suites, worker release contract ve closure state.",
    prerequisites: ["4.1-4.4 VERIFIED", "tum Phase 4 output/evidence digestleri gecerli"],
    affectedComponents: ["audit state machine", "phase closure evidence", "next phase gate"],
    affectedFiles: ["docs/system-audit/phase-4/*", ".manu-runtime/system-audit/phase-4/*", "tools/system-audit/phase-4/*"],
    architectureDecisions: [
      "Phase 4 sadece tum stage operation listeleri PASS, digestler gecerli ve final suites PASS ise CLOSED olur.",
      "Production, linked Supabase, WhatsApp real egress, Z.ai real egress ve raw media transferi bu audit kosusunda false kalir.",
      "Closure sonraki faz kilidini acar; Phase 5 implementasyonu bu fazin parcasi degildir.",
    ],
    operations: [
      "4.1-4.4 state, matrix ve evidence digestlerini yeniden hesapla; stale dosyayi blocker yap.",
      "Final worker release, messaging, provider security, media security ve lifecycle closure suite'lerini tek final kosusunda calistir.",
      "Production/linked Supabase/real provider egress boundary'sinin mutation-free oldugunu kanitla.",
      "Tum stage operation durumlarini PASS olarak kaydet; blocker varsa closure yazma ve Phase 5 kilidini acma.",
      "worker-messaging-ai-media-closure.json, phase-4-closure.json ve CLOSED state'i source commit ile yaz.",
    ],
    technicalMethods: ["SHA-256 digest reconciliation", "final grouped Vitest run", "mutation boundary assertion", "state machine closure"],
    dataFlow: "stage matrices/evidence -> digest reconciliation -> final suites -> mutation boundary -> closure output -> phase state CLOSED -> Phase 5 unlocked.",
    dependencies: ["4.1-4.4 matrices/evidence", "worker release contracts", "security migration contracts"],
    errorAndBoundaryCases: ["stale evidence", "failed final test", "missing stage", "remote mutation flag", "real egress flag", "incomplete operation list"],
    tests: ["production-worker-release-contracts.test.ts", "phase-85-stage-4b3-closure.test.ts", "phase-85-stage-4b4-closure.test.ts", "phase-85-stage-4c-closure.test.ts", "whatsapp-real-migration-contract.test.ts", "production-ai-media-security-migration-contract.test.ts"],
    verificationCriteria: ["all five stages VERIFIED", "all digests valid", "final tests PASS", "mutation boundary production=false linkedSupabase=false realEgress=false"],
    completionCriteria: "Phase 4 CLOSED ve nextPhaseUnlocked=true; bundan sonra Phase 5 uygulanabilir fakat bu komut Phase 5'e gecmez.",
  },
];

export function getPhase4Stage(stageId) {
  const stage = PHASE_4_STAGES.find((stage) => stage.id === stageId);
  if (!stage) throw new Error(`unsupported_phase_4_stage:${stageId}`);
  return stage;
}
