import { SAFETY_CLASSIFIER_VERSION } from "dietitian-ai-assistant-architecture";
import type { ClientRecord, ConversationRecord, ManuAppState, MessageRecord } from "./types";
import { completeSafetyChecklist, emptySafetyChecklist } from "./safety-checklist";
import { DEFAULT_LANGUAGE } from "./languages";

export const DEMO_TENANT_ID = "tenant-manu-demo";
export const DEMO_DIETITIAN_ID = "dietitian-ayse";
export const DEMO_FORM_SCHEMA_ID = "00000000-0000-4000-8000-000000000501";

const createdAt = "2026-05-22T09:00:00.000Z";

export function createInitialState(): ManuAppState {
  const clients: ClientRecord[] = [
    {
      id: "client-mert",
      tenantId: DEMO_TENANT_ID,
      dietitianId: DEMO_DIETITIAN_ID,
      lifecycleStatus: "active",
      removedAt: null,
      fullName: "Mert Kaya",
      primaryPhoneE164: "+905551110001",
      communicationLanguage: DEFAULT_LANGUAGE,
      selectedPersonaId: "balanced_coach",
      aiStatus: "active",
      aiMode: "autopilot",
      aiActiveFrom: null,
      aiActiveUntil: null,
      healthProfile: {
        goal: "Fat loss with steady meal adherence",
        preferredLanguage: "Turkish",
        adultStatus: "adult",
        diagnosedConditionFlag: false,
        medicationOrSupplementFlag: false,
        pregnancyOrBreastfeedingFlag: false,
        eatingDisorderRiskFlag: false,
      },
      dietPlan: {
        summary: "Three meals, one planned snack, no peanut suggestions.",
        breakfast: "Eggs, greens, whole grain bread",
        lunch: "Grilled chicken salad",
        dinner: "Vegetable soup and yogurt",
      },
      allergies: ["peanut"],
      restrictedFoods: [],
      clinicalRiskNotes: [],
      pinnedNotes: ["Avoid peanut suggestions.", "Prefers practical swaps."],
      channel: "whatsapp",
      channelUserId: "+905551110001",
      channelPermission: "ready",
      mandatorySafetyComplete: true,
      safetyChecklist: completeSafetyChecklist(),
      humanTakeoverLocked: false,
      redRiskLock: { status: "none" },
      contextRevision: 1,
      createdAt,
    },
    {
      id: "client-elif",
      tenantId: DEMO_TENANT_ID,
      dietitianId: DEMO_DIETITIAN_ID,
      lifecycleStatus: "active",
      removedAt: null,
      fullName: "Elif Demir",
      primaryPhoneE164: "+905551110002",
      communicationLanguage: DEFAULT_LANGUAGE,
      selectedPersonaId: "warm_supporter",
      aiStatus: "active",
      aiMode: "copilot",
      aiActiveFrom: null,
      aiActiveUntil: null,
      healthProfile: {
        goal: "Balanced nutrition during a busy work schedule",
        preferredLanguage: "Turkish",
        adultStatus: "adult",
        diagnosedConditionFlag: false,
        medicationOrSupplementFlag: true,
        pregnancyOrBreastfeedingFlag: false,
        eatingDisorderRiskFlag: false,
      },
      dietPlan: {
        summary: "Flexible plate method with protein at lunch and dinner.",
        breakfast: "Yogurt, oats, berries",
      },
      allergies: [],
      restrictedFoods: ["shellfish"],
      clinicalRiskNotes: ["Supplement questions require dietitian review."],
      pinnedNotes: ["Respond gently and keep drafts short."],
      channel: "telegram",
      channelUserId: "elif_telegram",
      channelPermission: "ready",
      mandatorySafetyComplete: true,
      safetyChecklist: completeSafetyChecklist(),
      humanTakeoverLocked: false,
      redRiskLock: { status: "none" },
      contextRevision: 1,
      createdAt,
    },
    {
      id: "client-deniz",
      tenantId: DEMO_TENANT_ID,
      dietitianId: DEMO_DIETITIAN_ID,
      lifecycleStatus: "active",
      removedAt: null,
      fullName: "Deniz Arslan",
      primaryPhoneE164: "+905551110003",
      communicationLanguage: DEFAULT_LANGUAGE,
      selectedPersonaId: "clinical_formal",
      aiStatus: "passive",
      aiMode: "manual",
      aiActiveFrom: null,
      aiActiveUntil: null,
      healthProfile: {
        goal: "Post-consultation follow-up",
        preferredLanguage: "Turkish",
        adultStatus: "unknown",
        diagnosedConditionFlag: false,
        medicationOrSupplementFlag: false,
        pregnancyOrBreastfeedingFlag: false,
        eatingDisorderRiskFlag: false,
      },
      dietPlan: {
        summary: "",
      },
      allergies: [],
      restrictedFoods: [],
      clinicalRiskNotes: [],
      pinnedNotes: [],
      channel: "whatsapp",
      channelUserId: "+905551110003",
      channelPermission: "pending",
      mandatorySafetyComplete: false,
      safetyChecklist: emptySafetyChecklist(),
      humanTakeoverLocked: false,
      redRiskLock: { status: "none" },
      contextRevision: 1,
      createdAt,
    },
  ];

  const conversations: ConversationRecord[] = clients.map((client) => ({
    id: `conversation-${client.id}`,
    tenantId: DEMO_TENANT_ID,
    dietitianId: DEMO_DIETITIAN_ID,
    clientId: client.id,
    channel: client.channel,
    rollingSummary: "Local simulator conversation. No real channel is connected.",
    memoryVersion: "memory-v1",
    memoryRevision: 1,
    memoryStale: false,
  }));

  const messages: MessageRecord[] = [
    {
      id: "message-seed-1",
      tenantId: DEMO_TENANT_ID,
      conversationId: "conversation-client-mert",
      sender: "client",
      origin: "client_inbound",
      body: "Bugun kahvaltida yumurta yerine ne yiyebilirim?",
      risk: "green",
      status: "stored",
      createdAt: "2026-05-22T09:10:00.000Z",
    },
    {
      id: "message-seed-2",
      tenantId: DEMO_TENANT_ID,
      conversationId: "conversation-client-mert",
      sender: "assistant",
      origin: "ai_generated",
      body: "Yumurta yerine lor peyniri ve bol yesillik iyi bir secenek olur.",
      sourceMessageId: "message-seed-1",
      generatedByAiDecisionId: "decision-seed-1",
      risk: "green",
      status: "sent",
      createdAt: "2026-05-22T09:11:00.000Z",
    },
  ];

  return {
    tenant: {
      id: DEMO_TENANT_ID,
      name: "MANU-AI Demo Clinic",
    },
    dietitian: {
      id: DEMO_DIETITIAN_ID,
      tenantId: DEMO_TENANT_ID,
      displayName: "Dyt. Ayse",
      timezone: "Europe/Istanbul",
      uiLanguage: DEFAULT_LANGUAGE,
    },
    voiceSamples: [],
    voiceProfiles: [],
    clientFormSchemas: [
      {
        id: DEMO_FORM_SCHEMA_ID,
        tenantId: DEMO_TENANT_ID,
        title: "Pilot intake",
        languageCode: DEFAULT_LANGUAGE,
        version: 1,
        status: "published",
        fields: [
          {
            id: "daily_routine",
            label: "Daily routine",
            type: "textarea",
            required: false,
            llmVisibility: "prompt_allowed",
          },
          {
            id: "private_note",
            label: "Private note",
            type: "textarea",
            required: false,
            llmVisibility: "never",
          },
        ],
        createdAt,
        publishedAt: createdAt,
      },
    ],
    clientFormResponses: [],
    clientContextUpdates: [],
    clients,
    conversations,
    messages,
    aiDecisions: [
      {
        id: "decision-seed-1",
        tenantId: DEMO_TENANT_ID,
        conversationId: "conversation-client-mert",
        clientId: "client-mert",
        mode: "autopilot",
        aiStatus: "active",
        personaId: "balanced_coach",
        risk: "green",
        model: "gemini-1.5-flash",
        promptVersion: "manu-prompt-v0.1.0",
        providerAttempted: true,
        providerId: "mock-local-provider-v0",
        providerStatus: "ok",
        providerErrorCode: null,
        sendStatus: "legacy_sent_unverified",
        contextManifest: null,
        providerOutputSafety: null,
        tokenBudget: null,
        action: "sent",
        blockedReason: null,
        qualityIssues: [],
        reasons: [],
        createdAt: "2026-05-22T09:11:00.000Z",
      },
    ],
    riskAssessments: [
      {
        id: "risk-assessment-seed-1",
        tenantId: DEMO_TENANT_ID,
        conversationId: "conversation-client-mert",
        messageId: "message-seed-1",
        level: "green",
        reasons: [],
        classifierVersion: SAFETY_CLASSIFIER_VERSION,
        createdAt: "2026-05-22T09:10:00.000Z",
      },
    ],
    handoffCases: [],
    auditEvents: [],
    notifications: [],
    inboundQuarantines: [],
    dataRequests: [],
    internalCopilotMessages: [],
    internalCopilotToolCalls: [],
    processedSimulationKeys: ["seed-green"],
    lastSimulation: null,
  };
}

export function createBlankClient(overrides: Partial<ClientRecord> = {}): ClientRecord {
  const id = crypto.randomUUID();
  return {
    id,
    tenantId: DEMO_TENANT_ID,
    dietitianId: DEMO_DIETITIAN_ID,
    lifecycleStatus: "active",
    removedAt: null,
    fullName: "New Client",
    primaryPhoneE164: null,
    communicationLanguage: DEFAULT_LANGUAGE,
    selectedPersonaId: "balanced_coach",
    aiStatus: "passive",
    aiMode: "copilot",
    aiActiveFrom: null,
    aiActiveUntil: null,
    healthProfile: {
      goal: "",
      preferredLanguage: "Turkish",
      adultStatus: "unknown",
      diagnosedConditionFlag: false,
      medicationOrSupplementFlag: false,
      pregnancyOrBreastfeedingFlag: false,
      eatingDisorderRiskFlag: false,
    },
    dietPlan: {
      summary: "",
    },
    allergies: [],
    restrictedFoods: [],
    clinicalRiskNotes: [],
    pinnedNotes: [],
    channel: "whatsapp",
    channelUserId: "",
    channelPermission: "pending",
    mandatorySafetyComplete: false,
    safetyChecklist: emptySafetyChecklist(),
    humanTakeoverLocked: false,
    redRiskLock: { status: "none" },
    contextRevision: 1,
    createdAt: new Date().toISOString(),
    ...overrides,
  };
}
